"use client";
import {useEffect,useRef,useState} from 'react';
import {initialContent} from '../content';
import {projectFields,ranges,textLabels,validContent,type SiteContent} from '../content-schema';
import {projects} from '../data';
import {assetPath} from '../paths';
import './studio.css';
const API='https://aform-studio-api.2975166565.workers.dev';
type Loaded={content:SiteContent;sha:string};
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object';
const loaded=(x:unknown):x is Loaded=>object(x)&&validContent(x.content)&&typeof x.sha==='string';
export default function Studio(){
 const [content,setContent]=useState<SiteContent>(initialContent),[past,setPast]=useState<SiteContent[]>([]),[future,setFuture]=useState<SiteContent[]>([]);
 const [tab,setTab]=useState('text'),[page,setPage]=useState(''),[width,setWidth]=useState('100%'),[message,setMessage]=useState('登录后开始编辑。所有更改先在预览中生效。');
 const [session,setSession]=useState(''),[sha,setSha]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[cloudDraft,setCloudDraft]=useState<Loaded|null>(null);
 const frame=useRef<HTMLIFrameElement>(null),popup=useRef<Window|null>(null),latest=useRef(content);
 useEffect(()=>{const controller=new AbortController();void fetch(API+'/health',{signal:controller.signal}).then(r=>r.json()).then(d=>{if(object(d)&&!d.ready)setMessage('等待首次 GitHub 登录配置：请按 EDITOR-SETUP.md 添加应用密钥。')}).catch(()=>{if(!controller.signal.aborted)setMessage('无法连接后台，请检查网络后重试。')});return()=>controller.abort()},[]);
 useEffect(()=>{latest.current=content;frame.current?.contentWindow?.postMessage({type:'aform-preview',content},window.location.origin)},[content,past]);
 async function api(path:string,token=session,body?:unknown){if(!API)throw Error('后台等待开通，请先完成 Cloudflare 与 GitHub 登录配置。');const r=await fetch(API+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(object(d)&&typeof d.error==='string'?d.error:'请求失败，请重试');return d;}
 function change(next:SiteContent){setPast(p=>[...p.slice(-49),content]);setFuture([]);setContent(next);setMessage('预览已更新 · 尚未同步');}
 async function load(token:string){const d=await api('/content',token);if(!loaded(d))throw Error('远程内容格式不兼容');setContent(d.content);setSha(d.sha);setPast([]);setFuture([]);const draft=await api('/draft',token);setCloudDraft(loaded(draft)?draft:null);setMessage('已加载 GitHub 最新版本，可开始编辑。');}
 useEffect(()=>{function receive(e:MessageEvent){if(e.source===frame.current?.contentWindow&&e.origin===location.origin&&e.data?.type==='aform-ready')frame.current.contentWindow?.postMessage({type:'aform-preview',content:latest.current},location.origin);if(API&&e.origin===new URL(API).origin&&e.source===popup.current&&e.data?.type==='aform-auth'&&typeof e.data.session==='string'){setSession(e.data.session);void load(e.data.session).catch(err=>setMessage(err.message));popup.current?.close();}}
 window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);
 // Login callback is bound to the exact opened window and trusted backend origin.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function login(){if(!API){setMessage('编辑器已准备好；安全登录正在等待 Cloudflare 和 GitHub 应用配置。');return;}popup.current=window.open(API+'/auth/start','aform-login','width=640,height=760');if(!popup.current)setMessage('请允许弹出窗口后再次登录。');}
 async function action(kind:'save'|'publish'){if(!validContent(content)){setMessage('请填写全部文字，并保持数值在允许范围内。');return;}setBusy(true);try{if(kind==='save'){await api('/draft',session,{content,sha});setMessage('云端草稿已保存，其他设备登录后可恢复。');}else{const d=await api('/publish',session,{content,sha});if(!object(d)||typeof d.sha!=='string')throw Error('无法确认同步结果');setSha(d.sha);setMessage('已同步 GitHub，正式网站正在构建。请在“发布进度”查看结果。');}}catch(e){setMessage(e instanceof Error?e.message:'操作失败')}finally{setBusy(false)}}
 const selected=projects.find(p=>p.slug===page);
 return <main className="studio" id="main-content"><header className="studio-header"><a href={assetPath('/')} className="studio-brand">A / FORM<span>STUDIO</span></a><div className="studio-owner">个人网站编辑器 <span>MIENA1-A2</span></div><div className="studio-actions"><a href="https://github.com/MIENA1-A2/a-form-portfolio/actions" target="_blank" rel="noreferrer">发布进度 ↗</a>{session?<><button onClick={()=>{void api('/logout',session,{}).catch(()=>{});setSession('');setCloudDraft(null);setMessage('已退出。请重新登录继续编辑。')}}>退出</button><button disabled={busy} onClick={()=>void action('save')}>保存草稿</button><button className="primary" disabled={busy} onClick={()=>void action('publish')}>{busy?'处理中…':'同步并发布 ↗'}</button></>:<button className="primary" onClick={()=>void login()}>使用 GitHub 登录 ↗</button>}</div></header>
 <div className="studio-toolbar"><div className="studio-page"><span>正在预览</span><select aria-label="预览页面" value={page} onChange={e=>setPage(e.target.value)}><option value="">首页</option>{projects.map(p=><option key={p.slug} value={p.slug}>{p.name}</option>)}</select></div><div className="studio-devices">{[['100%','桌面'],['768px','平板'],['390px','手机']].map(([v,label])=><button aria-pressed={width===v} key={v} onClick={()=>setWidth(v)}>{label}</button>)}<button onClick={()=>setRevision(r=>r+1)}>重播动效 ↻</button></div><div><button disabled={!session||!past.length} onClick={()=>{setFuture(f=>[content,...f]);setContent(past[past.length-1]);setPast(p=>p.slice(0,-1))}}>↶ 撤销</button><button disabled={!session||!future.length} onClick={()=>{setPast(p=>[...p,content]);setContent(future[0]);setFuture(f=>f.slice(1))}}>↷ 重做</button></div></div>
 <div className="studio-body"><aside className="studio-inspector"><div className="studio-tabs">{[['text','文字'],['design','排版'],['motion','动效']].map(([v,label])=><button key={v} aria-pressed={tab===v} onClick={()=>setTab(v)}>{label}</button>)}</div>{!session&&<div className="studio-lock"><strong>你的设计工作台。</strong><p>调整 → 实时预览 → 同步上线。只有指定 GitHub 账号能保存或发布。</p><button onClick={()=>void login()}>登录并开始编辑 ↗</button></div>}
 {cloudDraft&&session&&<div className="studio-draft"><p>有一份云端草稿</p><button onClick={()=>{change(cloudDraft.content);setSha(cloudDraft.sha);setCloudDraft(null);setMessage('草稿已恢复；发布前会检查是否与远程版本冲突。')}}>恢复草稿</button><button onClick={()=>setCloudDraft(null)}>暂不恢复</button></div>}
 <fieldset disabled={!session||busy}>{tab==='text'&&<><div className="studio-section-title">{selected?selected.name:'首页内容'}<small>换行会保留在页面中</small></div>{selected?Object.entries(projectFields).map(([key,label])=><label key={key}>{label}<textarea rows={key==='narrative'?6:2} maxLength={2000} value={content.projects[page]?.[key as keyof typeof projectFields]??selected[key as keyof typeof projectFields]} onChange={e=>change({...content,projects:{...content.projects,[page]:{...content.projects[page],[key]:e.target.value}}})}/></label>):Object.entries(textLabels).map(([key,label])=><label key={key}>{label}<textarea maxLength={2000} rows={key.includes('Body')?4:2} value={content.text[key as keyof typeof textLabels]} onChange={e=>change({...content,text:{...content.text,[key]:e.target.value}})}/></label>)}</>}
 {tab==='design'&&<><div className="studio-section-title">文字与空间<small>标题设置作用于首页，正文和间距作用于作品区</small></div>{[['headingScale','首屏字号比例',.01],['tracking','标题字距',.005],['lineHeight','标题行高',.01],['spacing','章节间距',.05],['bodySize','作品正文字号',1]].map(([k,label,step])=>{const key=k as keyof typeof ranges;return <label key={key}>{label}<output>{content.design[key as keyof SiteContent['design']]}</output><input type="range" min={ranges[key][0]} max={ranges[key][1]} step={step} value={content.design[key as keyof SiteContent['design']]} onChange={e=>change({...content,design:{...content.design,[key]:Number(e.target.value)}})}/></label>})}<div className="studio-section-title">色彩</div>{[['blue','主色'],['paper','纸张色'],['lime','点缀色']].map(([key,label])=><label className="color-field" key={key}>{label}<input type="color" value={content.design[key as 'blue']} onChange={e=>change({...content,design:{...content.design,[key]:e.target.value}})}/><code>{content.design[key as 'blue']}</code></label>)}</>}
 {tab==='motion'&&<><div className="studio-section-title">动效编排<small>系统“减少动态效果”优先于这些设置</small></div><label className="toggle-field">启用动效<input type="checkbox" checked={content.motion.enabled} onChange={e=>change({...content,motion:{...content.motion,enabled:e.target.checked}})}/></label>{[['duration','进入时长（秒）',.05],['distance','进入位移（像素）',1],['hoverScale','悬停缩放',.005],['parallax','首屏视差强度',.05]].map(([k,label,step])=>{const key=k as keyof typeof ranges;return <label key={key}>{label}<output>{String(content.motion[key as keyof SiteContent['motion']])}</output><input type="range" min={ranges[key][0]} max={ranges[key][1]} step={step} value={Number(content.motion[key as keyof SiteContent['motion']])} onChange={e=>change({...content,motion:{...content.motion,[key]:Number(e.target.value)}})}/></label>})}<p className="studio-help">修改后点击“重播动效”，或在预览中滚动查看。动效设置不会强制覆盖访客的无障碍偏好。</p></>}
 </fieldset></aside><section className="studio-canvas" aria-label="实时网站预览"><div className="studio-preview-label"><span>LIVE CANVAS / {selected?'PROJECT':'HOME'}</span><span>预览不会自动发布</span></div><iframe key={page+revision} ref={frame} title="作品集实时预览" src={assetPath(page?'/work/'+page+'/?preview=1':'/?preview=1')} style={{width}} onLoad={()=>frame.current?.contentWindow?.postMessage({type:'aform-preview',content},location.origin)}/></section></div><footer className="studio-status" role="status"><span className="studio-dot"/>{message}<span className="studio-version">A / FORM STUDIO · 01</span></footer></main>
}
