'use client';
import {useEffect,useState,useRef,type PointerEvent} from 'react';
import {migrate,patchBox,boxAt,updateLayer,widths,makeLayer,validDocument,type Breakpoint,type Document,type Layer,type Section,type Box} from './document';
import {draftStore,importImage,sanitizeSvg} from './assets';
import {assetPath} from '../paths';
import Renderer from './renderer';
import CloudSync from './cloud-sync';
import {RevealControls,SurfaceControls,ModelMaterialControls} from './effects-controls';
import './workbench.css';

function NumberField({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(value:number)=>void}){
 return <label>{label}<input key={String(value)} type="number" defaultValue={Number(value.toFixed(3))} min={min} max={max} step={step} onBlur={e=>{const n=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(n))onChange(Math.max(min,Math.min(max,n)));else e.target.value=String(value)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/></label>;
}
type Fields=Array<[string,string,number,number,number]>;
const boxFields:Fields=[['x','X',-5000,10000,1],['y','Y',-5000,20000,1],['width','宽度',10,5000,1],['height','高度',10,10000,1],['rotation','旋转',-360,360,1],['opacity','透明度',0,1,.01],['radius','圆角',0,1000,1]];
const textFields:Fields=[['fontSize','字号',8,600,1],['lineHeight','行高',.5,3,.01],['tracking','字距',-.2,1,.01]];
const modelFields:Fields=[['depth','挤出厚度',1,100,1],['bevel','倒角',0,20,.5],['metalness','金属度',0,1,.01],['roughness','粗糙度',0,1,.01],['transmission','透射',0,1,.01],['ior','折射率',1,2.5,.01],['clearcoat','清漆',0,1,.01],['pointer','鼠标倾斜 °',0,10,.5]];
const motionFields:Fields=[['distance','进入位移',0,100,1],['duration','时长 / 秒',.1,5,.05],['delay','延迟 / 秒',0,5,.05],['hover','悬停缩放',1,1.2,.01]];
function FieldsView({fields,values,update}:{fields:Fields;values:object;update:(key:string,value:number)=>void}){return fields.map(([k,label,min,max,step])=><NumberField key={k} label={label} min={min} max={max} step={step} value={(values as Record<string,number>)[k]} onChange={v=>update(k,v)}/>)}
export default function Workbench(){
 const [doc,setDoc]=useState<Document>(migrate),[pageId,setPage]=useState('home'),[selected,setSelected]=useState(''),[sectionId,setSectionId]=useState(''),[bp,setBp]=useState<Breakpoint>('desktop'),[zoom,setZoom]=useState(.5),[preview,setPreview]=useState(false),[past,setPast]=useState<Document[]>([]),[future,setFuture]=useState<Document[]>([]),[message,setMessage]=useState('修改后可保存云端；开启自动更新后同步到公开网站'),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[assetsOpen,setAssetsOpen]=useState(false),[pane,setPane]=useState('canvas');
 const [dragging,setDragging]=useState(false);
 const gesture=useRef<{doc:Document;id:string;x:number;y:number;resize:boolean;moved:boolean}|null>(null),imageInput=useRef<HTMLInputElement>(null),svgInput=useRef<HTMLInputElement>(null),jsonInput=useRef<HTMLInputElement>(null),stage=useRef<HTMLElement>(null);
 const page=doc.pages.find(p=>p.id===pageId)||doc.pages[0],layer=page.sections.flatMap(s=>s.children).find(l=>l.id===selected),section=page.sections.find(s=>s.children.some(l=>l.id===selected))||page.sections.find(s=>s.id===sectionId)||page.sections[0],box=layer?boxAt(layer,bp):null;
 function change(next:Document){if(JSON.stringify(next)===JSON.stringify(doc))return;if(!validDocument(next)){setMessage('修改超出文档限制，未应用；请减少素材或检查数值。');return;}setPast(p=>[...p.slice(-29),doc]);setFuture([]);setDoc(next);setDirty(true);setMessage('画布已修改 · 尚未保存');}
 function undo(){if(!past.length)return;setFuture(f=>[doc,...f]);setDoc(past[past.length-1]);setPast(p=>p.slice(0,-1));setDirty(true);}
 function redo(){if(!future.length)return;setPast(p=>[...p,doc]);setDoc(future[0]);setFuture(f=>f.slice(1));setDirty(true);}
 function editLayer(update:(l:Layer)=>Layer){if(!layer?.locked)change(updateLayer(doc,selected,update));}
 function editBox(patch:Partial<Box>){if(!layer?.locked)change(patchBox(doc,selected,bp,patch));}
 function editSection(patch:Partial<Section>){change({...doc,pages:doc.pages.map(p=>p.id!==page.id?p:{...p,sections:p.sections.map(s=>s.id===section.id?{...s,...patch}:s)})});}
 function add(type:Layer['type']){const l=makeLayer(type,crypto.randomUUID(),type==='text'?'YOUR NEXT IDEA':'',{x:48,y:80,width:type==='text'?600:450,height:type==='text'?140:450});editSection({children:[...section.children,l]});setSelected(l.id);}
 function remove(){if(!layer||layer.locked)return;editSection({children:section.children.filter(l=>l.id!==selected)});setSelected('');}
 function duplicate(){if(!layer)return;const next={...structuredClone(layer),id:crypto.randomUUID(),name:layer.name+' 副本',box:{...layer.box,x:layer.box.x+24,y:layer.box.y+24}};editSection({children:[...section.children,next]});setSelected(next.id);}
 function reorder(direction:number){const children=[...section.children],index=children.findIndex(l=>l.id===selected),to=index+direction;if(to<0||to>=children.length)return;[children[index],children[to]]=[children[to],children[index]];editSection({children});}
 function drag(e:PointerEvent,id:string,resize=false){if(e.button!==0||preview)return;const parent=page.sections.find(s=>s.children.some(l=>l.id===id));if(parent?.layout!=='free'&&!resize){setMessage('自动布局中请调整图层顺序，或切换自由布局。');return;}e.currentTarget.setPointerCapture(e.pointerId);setDragging(true);gesture.current={doc,id,x:e.clientX,y:e.clientY,resize,moved:false};}
 function move(e:PointerEvent){const g=gesture.current;if(!g)return;const l=g.doc.pages.flatMap(p=>p.sections.flatMap(s=>s.children)).find(l=>l.id===g.id)!,b=boxAt(l,bp),dx=(e.clientX-g.x)/zoom,dy=(e.clientY-g.y)/zoom;if(Math.abs(dx)+Math.abs(dy)<3&&!g.moved)return;g.moved=true;const snap=(n:number)=>Math.round(n/(e.altKey?1:8))*(e.altKey?1:8);setDoc(patchBox(g.doc,g.id,bp,g.resize?{width:Math.min(5000,Math.max(10,snap(b.width+dx))),height:Math.min(10000,Math.max(10,snap(b.height+dy)))}:{x:Math.max(-5000,Math.min(10000,snap(b.x+dx))),y:Math.max(-5000,Math.min(20000,snap(b.y+dy)))}));}
 function end(cancel=false){setDragging(false);const g=gesture.current;if(!g)return;if(cancel)setDoc(g.doc);else if(g.moved){setPast(p=>[...p.slice(-29),g.doc]);setFuture([]);setDirty(true);setMessage('位置已更新 · 8 px 吸附，按 Alt 自由拖动');}gesture.current=null;}
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(preview||(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable=true]')))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}else if(e.key==='Delete')remove();else if(layer&&!layer.locked&&box&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=e.shiftKey?10:1;editBox({x:box.x+(e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0),y:box.y+(e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0)});}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 async function run(task:()=>Promise<void>){setBusy(true);try{await task()}catch(e){setMessage(e instanceof Error?e.message:'操作失败，请重试')}finally{setBusy(false)}}
 function checkSvg(value:Document){for(const l of value.pages.flatMap(p=>p.sections.flatMap(s=>s.children)))if(l.model.svg)sanitizeSvg(l.model.svg);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='aform-studio-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已导出文档与素材，可在另一台设备导入。');}
 async function upload(file:File,svg=false){if(!layer||layer.locked||layer.type==='text')throw Error('请先选择未锁定的图片或模型图层。');if(svg){if(file.size>100000)throw Error('SVG 上限 100 KB。');const source=sanitizeSvg(await file.text());editLayer(l=>({...l,type:'model',name:file.name,model:{...l.model,svg:source}}));}else{const src=await importImage(file);editLayer(l=>({...l,src,alt:file.name.replace(/\.[^.]+$/,'')}));}}
 const imageLayers=doc.pages.flatMap(p=>p.sections.flatMap(s=>s.children)).filter(l=>l.type!=='text'),assets=[...new Map(imageLayers.map(l=>[l.src,l])).values()];
 return <main translate="no" className={'notranslate v2 pane-'+pane+' '+(preview?'v2-preview':'')} id="main-content" onPointerMove={move} onPointerUp={()=>end()} onPointerCancel={()=>end(true)}>
  <header className="v2-header"><strong>A / FORM <span>VISUAL STUDIO</span></strong><span className="v2-badge">V2 · 可视化工作台</span><div className="v2-actions"><button disabled={!past.length||busy} onClick={undo}>↶ 撤销</button><button disabled={!future.length||busy} onClick={redo}>↷ 重做</button><button disabled={busy} onClick={()=>void run(async()=>{await draftStore('write',doc);setDirty(false);setMessage('已保存本机草稿 · 尚未同步云端');})}>保存本机</button><button className="v2-primary" onClick={()=>{setPreview(v=>!v);setRevision(r=>r+1)}}>{preview?'返回编辑':'预览效果 ↗'}</button></div></header>
  <CloudSync doc={doc} dirty={dirty} blocked={busy||dragging} onLoad={value=>{setPast(p=>[...p.slice(-29),doc]);setFuture([]);setDoc(value);setDirty(false);setSelected('');setSectionId('');}} onSaved={snapshot=>{if(JSON.stringify(snapshot)===JSON.stringify(doc))setDirty(false);}}/>
  <div className="v2-toolbar"><div>{(['text','image','model'] as const).map((t,i)=><button disabled={preview||busy} key={t} onClick={()=>add(t)}>＋ {['文字','图片','3D'][i]}</button>)}<button onClick={()=>setRevision(r=>r+1)}>重播</button></div><div>{(['desktop','tablet','mobile'] as Breakpoint[]).map((v,i)=><button aria-pressed={bp===v} key={v} onClick={()=>setBp(v)}>{['桌面','平板','手机'][i]}</button>)}<button onClick={()=>{if(stage.current)setZoom(Math.max(.15,Math.min(1,(stage.current.clientWidth-70)/widths[bp])))}}>适应</button><select aria-label="画布缩放" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[.25,.35,.5,.65,.75,1].map(z=><option key={z} value={z}>{Math.round(z*100)}%</option>)}</select></div></div>
  <div className="v2-mobile-tabs">{[['layers','图层'],['canvas','画布'],['properties','属性']].map(([v,label])=><button key={v} aria-pressed={pane===v} onClick={()=>setPane(v)}>{label}</button>)}</div><div className="v2-body" inert={busy}><aside className="v2-left"><h2>页面</h2>{doc.pages.map(p=><button className="v2-page-button" aria-pressed={page.id===p.id} key={p.id} onClick={()=>{setPage(p.id);setSelected('');setSectionId('');stage.current?.scrollTo(0,0)}}>{p.name}<span>↗</span></button>)}<div className="v2-left-tabs"><button aria-pressed={!assetsOpen} onClick={()=>setAssetsOpen(false)}>图层</button><button aria-pressed={assetsOpen} onClick={()=>setAssetsOpen(true)}>素材</button></div>{assetsOpen?<div className="v2-assets"><p>选择图片或模型后点击素材替换。</p>{assets.map(a=><button key={a.src} disabled={!layer||layer.type==='text'||layer.locked} onClick={()=>editLayer(l=>({...l,src:a.src}))}><img src={a.src.startsWith('/')?assetPath(a.src):a.src} alt={a.alt}/><span>{imageLayers.filter(l=>l.src===a.src).length} 处使用</span></button>)}</div>:page.sections.map(s=><div key={s.id} className="v2-layer-group"><button className="v2-section-button" aria-pressed={!selected&&section.id===s.id} onClick={()=>{setSectionId(s.id);setSelected('')}}>▦ {s.name}</button>{s.children.map(l=><button aria-pressed={selected===l.id} key={l.id} onClick={()=>{setSelected(l.id);stage.current?.querySelector(`[data-layer-id="${l.id}"]`)?.scrollIntoView({block:'center',inline:'center',behavior:'instant'})}}><span>{l.type==='text'?'T':l.type==='model'?'◇':'▧'}</span>{l.name}{l.hidden?' · 隐藏':''}{l.locked?' · 锁定':''}</button>)}</div>)}<div className="v2-files"><button disabled={busy} onClick={()=>void run(async()=>{const value=await draftStore('read');if(!validDocument(value))throw Error('没有可恢复的本机 V2 草稿。');checkSvg(value);change(value);setPage(value.pages[0].id);setSelected('');setMessage('已恢复本机草稿，仍可撤销。');})}>恢复本机草稿</button><button onClick={download}>导出备份 ↓</button><button onClick={()=>jsonInput.current?.click()}>导入备份 ↑</button></div></aside>
   <section ref={stage} className="v2-stage" aria-label="可编辑画布" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f&&!preview)void run(()=>upload(f,f.name.toLowerCase().endsWith('.svg')));}}><div className="v2-stage-caption">{page.name} <span>{widths[bp]} PX / {preview?'PREVIEW':'EDIT'}</span></div><div style={{width:widths[bp],zoom}}><Renderer revision={revision} page={page} bp={bp} selected={selected} editing={!preview} onSelect={setSelected} onDrag={drag} onText={(id,text)=>change(updateLayer(doc,id,l=>({...l,text})))}/></div></section>
   <aside className="v2-right"><h2>{layer?.name||section.name}</h2><div className="v2-notice">{bp==='desktop'?'桌面为基础样式。':'当前只修改'+(bp==='tablet'?'平板':'手机')+'样式。'}<br/>选中元素后修改，预览查看动效。</div>{layer&&box?<>
    <label>图层名称<input disabled={layer.locked} value={layer.name} maxLength={200} onChange={e=>editLayer(l=>({...l,name:e.target.value}))}/></label><div className="v2-row"><button aria-pressed={layer.hidden} onClick={()=>change(updateLayer(doc,selected,l=>({...l,hidden:!l.hidden})))}>{layer.hidden?'显示':'隐藏'}</button><button aria-pressed={layer.locked} onClick={()=>change(updateLayer(doc,selected,l=>({...l,locked:!l.locked})))}>{layer.locked?'解锁':'锁定'}</button></div>
    <fieldset disabled={layer.locked||busy}><h3>位置与尺寸</h3><FieldsView fields={boxFields} values={box} update={(k,v)=>editBox({[k]:v})}/><div className="v2-row"><button onClick={()=>reorder(-1)}>下移图层</button><button onClick={()=>reorder(1)}>上移图层</button></div>
    <div className="v2-row"><button onClick={duplicate}>复制</button><button onClick={remove}>删除</button></div>
    {layer.type==='text'?<><h3>文字排版</h3><textarea aria-label="文字内容" key={selected+layer.text} defaultValue={layer.text} maxLength={10000} onBlur={e=>editLayer(l=>({...l,text:e.target.value}))}/><FieldsView fields={textFields} values={box} update={(k,v)=>editBox({[k]:v})}/><label>文字颜色<input type="color" value={box.color} onChange={e=>editBox({color:e.target.value})}/></label><label>对齐<select value={box.align} onChange={e=>editBox({align:e.target.value as Box['align']})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label></>:<><h3>{layer.type==='model'?'静态替代图':'图片'}</h3><button className="v2-full" onClick={()=>imageInput.current?.click()}>上传并替换图片 ↑</button><p>可拖入图片，保留框架位置。最长边压缩至 2048 px。</p><label>显示方式<select value={box.fit} onChange={e=>editBox({fit:e.target.value as Box['fit']})}><option value="cover">裁切填充</option><option value="contain">完整显示</option></select></label><FieldsView fields={[["focalX","焦点 X %",0,100,1],["focalY","焦点 Y %",0,100,1]]} values={box} update={(k,v)=>editBox({[k]:v})}/><label>替代文字<input value={layer.alt} maxLength={2000} onChange={e=>editLayer(l=>({...l,alt:e.target.value}))}/></label></>}
    {layer.type==='model'&&<><h3>SVG → 立体模型</h3><button className="v2-full" onClick={()=>svgInput.current?.click()}>导入 SVG 轮廓 ↑</button><p>仅支持闭合轮廓，不支持滤镜、外链和未转曲文字。手机使用静态替代图。</p>{layer.model.svg&&<button className="v2-full" onClick={()=>editLayer(l=>({...l,model:{...l.model,svg:''}}))}>恢复默认雕塑</button>}<label>材质颜色<input type="color" value={layer.model.color} onChange={e=>editLayer(l=>({...l,model:{...l.model,color:e.target.value}}))}/></label><FieldsView fields={modelFields} values={layer.model} update={(k,v)=>editLayer(l=>({...l,model:{...l.model,[k]:v}}))}/><label>自动旋转<input type="checkbox" checked={layer.model.rotate} onChange={e=>editLayer(l=>({...l,model:{...l.model,rotate:e.target.checked}}))}/></label></>}
    {layer.type==='text'&&<RevealControls value={layer.motion} onChange={motion=>editLayer(l=>({...l,motion}))} onReplay={()=>{setPreview(true);setRevision(r=>r+1)}}/>}{layer.type==='model'?<ModelMaterialControls value={layer.model} onChange={model=>editLayer(l=>({...l,model}))}/>:<SurfaceControls value={layer.surface} image={layer.type==='image'} onChange={surface=>editLayer(l=>({...l,surface}))}/>}
    <h3>元素动效</h3><label>进入时淡入<input type="checkbox" checked={layer.motion.enter} onChange={e=>editLayer(l=>({...l,motion:{...l.motion,enter:e.target.checked}}))}/></label><FieldsView fields={motionFields} values={layer.motion} update={(k,v)=>editLayer(l=>({...l,motion:{...l.motion,[k]:v}}))}/><p>预览中生效，尊重系统“减少动态效果”。</p></fieldset>
   </>:<><h3>章节布局</h3><label>布局<select value={section.layout} onChange={e=>editSection({layout:e.target.value as Section['layout']})}><option value="free">自由画布</option><option value="row">自动横向</option><option value="column">自动纵向</option></select></label><NumberField label="章节高度" value={section.height} min={100} max={10000} onChange={height=>editSection({height})}/><NumberField label="间距" value={section.gap} min={0} max={300} onChange={gap=>editSection({gap})}/><NumberField label="内边距" value={section.padding} min={0} max={300} onChange={padding=>editSection({padding})}/><label>渐变背景<input type="checkbox" checked={section.backgroundMode==='gradient'} onChange={e=>editSection({backgroundMode:e.target.checked?'gradient':'solid'})}/></label><label>背景<input type="color" value={section.background} onChange={e=>editSection({background:e.target.value})}/></label><SurfaceControls value={section.surface} onChange={surface=>editSection({surface})}/><div className="v2-empty"><b>点选元素开始设计</b><p>拖动改变位置，右下角手柄调整尺寸。选中文字后可输入。方向键微调，Shift 加速，Alt 关闭吸附。</p></div></>}
   <div className="v2-notice">云端草稿仅本人可见。开启“自动更新线上”后，当前五个页面及图片会公开。</div></aside>
  </div><footer className="v2-status" role="status"><span>{`● ${busy?'处理中…':message}`}</span><span>{`${dirty?'未保存 · ':''}${page.sections.reduce((n,s)=>n+s.children.length,0)} 个图层 · ${bp}`}</span></footer>
  <input className="v2-hidden" ref={imageInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void run(()=>upload(f));e.target.value='';}}/><input className="v2-hidden" ref={svgInput} type="file" accept=".svg,image/svg+xml" onChange={e=>{const f=e.target.files?.[0];if(f)void run(()=>upload(f,true));e.target.value='';}}/><input className="v2-hidden" ref={jsonInput} type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{if(f.size>16_000_000)throw Error('备份超过 16 MB 限制。');const value:unknown=JSON.parse(await f.text());if(!validDocument(value))throw Error('备份格式不兼容或包含不安全内容。');checkSvg(value);change(value);setPage(value.pages[0].id);setSelected('');setMessage('备份已导入，可撤销。');});e.target.value='';}}/>
 </main>;
}
