import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function mod(file,deps={}){const exports={};const source=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;vm.runInNewContext(source,{exports,require:key=>deps[key],console});return exports;}
const data=mod('../app/data.ts'),effects=mod('../app/studio-next/effects.ts');
const d=mod('../app/studio-next/document.ts',{'../data':data,'./effects':effects,'../site-content.json':JSON.parse(readFileSync(new URL('../app/site-content.json',import.meta.url)))});

const layout=mod('../app/studio-next/layout.ts',{'./document':d});
test('constraint matrix stays inside narrow containers even with oversized margins',()=>{for(const width of [1,320,390,768,1024,1920])for(const mode of ['fixed','fill'])for(const anchor of ['free','left','center','right'])for(const margin of [0,18,300,1000]){const l=d.makeLayer('text','boundary','Text',{x:9000,width:5000,widthMode:mode,anchor,insetLeft:margin,insetRight:margin});const b=layout.resolveLayoutBox(l,'desktop',width);assert.ok(Number.isFinite(b.x)&&Number.isFinite(b.width));assert.ok(b.x>=0&&b.width>=1&&b.x+b.width<=width+0.00001,JSON.stringify({width,mode,anchor,margin,b}));}});
test('section padding leaves a positive content area at every viewport',()=>{for(const width of [1,320,390,768,1024,1920])for(const padding of [0,48,300]){const safe=layout.safePadding(padding,width);assert.ok(safe>=0);assert.ok(width-2*safe>=1);assert.ok(safe<=padding);}});
test('maximum width alone activates constraints consistently',()=>{const l=d.makeLayer('text','maximum','Text',{x:5000,width:1000,maxWidth:200});assert.equal(layout.hasLayoutRules(l.box),true);const b=layout.resolveLayoutBox(l,'desktop',320);assert.equal(b.width,200);assert.equal(b.x,120);});
test('legacy geometry scales without altering the stored document',()=>{const l=d.makeLayer('text','layout-test','Text',{x:100,y:80,width:400,height:200,fontSize:40});const before=JSON.stringify(l),b=layout.resolveLayoutBox(l,'desktop',720);assert.equal(b.x,50);assert.equal(b.width,200);assert.equal(b.fontSize,20);assert.equal(JSON.stringify(l),before);});
test('fill width honors asymmetric margins and maximum width',()=>{const l=d.makeLayer('text','layout-test','Text',{widthMode:'fill',insetLeft:30,insetRight:50,maxWidth:600,anchor:'center'});const b=layout.resolveLayoutBox(l,'desktop',1000);assert.equal(b.width,600);assert.equal(b.x,190);});
test('fixed width clamps to container and right anchor honors its margin',()=>{const l=d.makeLayer('text','layout-test','Text',{width:600,widthMode:'fixed',insetLeft:18,insetRight:18,anchor:'right'});const b=layout.resolveLayoutBox(l,'desktop',390);assert.equal(b.width,354);assert.equal(b.x,18);});
test('fixed sizing retains text size and height',()=>{const l=d.makeLayer('text','layout-test','Text',{widthMode:'fixed',height:120,fontSize:40});const b=layout.resolveLayoutBox(l,'desktop',1000);assert.equal(b.height,120);assert.equal(b.fontSize,40);});
test('reset one override preserves remaining overrides and desktop',()=>{let doc=d.migrate();const id=doc.pages[0].sections[0].children[0].id;doc=d.patchBox(doc,id,'mobile',{widthMode:'fill',fontSize:25});const before=JSON.stringify(doc.pages[0].sections[0].children[0].box);const next=d.resetBoxOverride(doc,id,'mobile','widthMode'),l=next.pages[0].sections[0].children[0];assert.equal(l.overrides.mobile.widthMode,undefined);assert.equal(l.overrides.mobile.fontSize,25);assert.equal(JSON.stringify(l.box),before);assert.equal(doc.pages[0].sections[0].children[0].overrides.mobile.widthMode,'fill');});
test('reset all overrides removes only targeted breakpoint',()=>{let doc=d.migrate();const id=doc.pages[0].sections[0].children[0].id;doc=d.patchBox(doc,id,'mobile',{fontSize:25});doc=d.patchBox(doc,id,'tablet',{fontSize:50});const next=d.resetBoxOverride(doc,id,'mobile'),l=next.pages[0].sections[0].children[0];assert.equal(l.overrides.mobile,undefined);assert.equal(l.overrides.tablet.fontSize,50);assert.equal(d.resetBoxOverride(doc,id,'desktop'),doc);});
test('new layout fields validate and reject invalid values',()=>{const doc=d.migrate(),s=doc.pages[0].sections[0],l=s.children[0];s.autoHeight=true;Object.assign(l.box,{widthMode:'fill',heightMode:'auto',anchor:'center',maxWidth:600,insetLeft:18,insetRight:18});assert.ok(d.validDocument(doc));for(const [key,value] of [['widthMode','bad'],['heightMode','bad'],['insetLeft',NaN],['maxWidth',Infinity]]){const copy=JSON.parse(JSON.stringify(doc));copy.pages[0].sections[0].children[0].box[key]=value;assert.equal(d.validDocument(copy),false,key);}s.autoHeight='bad';assert.equal(d.validDocument(doc),false);});
