import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function mod(file,deps={}){const exports={};const source=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;vm.runInNewContext(source,{exports,require:key=>deps[key],console});return exports;}
const data=mod('../app/data.ts'),effects=mod('../app/studio-next/effects.ts');
const d=mod('../app/studio-next/document.ts',{'../data':data,'./effects':effects,'../site-content.json':JSON.parse(readFileSync(new URL('../app/site-content.json',import.meta.url)))});
const s=mod('../app/studio-next/selection.ts',{'./document':d});
function fixture(){const doc=d.migrate();doc.pages[0].sections[0].children=[d.makeLayer('text','test-a','A',{x:10,y:20,width:100,height:50,fontSize:20}),d.makeLayer('image','test-b','',{x:200,y:100,width:150,height:100}),d.makeLayer('image','test-c','',{x:500,y:250,width:100,height:80})];return doc;}
const ids=['test-a','test-b','test-c'];
const layers=doc=>doc.pages[0].sections[0].children;
test('shift selection toggles and prevents cross-section coordinate mixing',()=>{const doc=fixture(),page=doc.pages[0];assert.equal(JSON.stringify(s.selectLayer(page,['test-a'],'test-b',true)),JSON.stringify(['test-a','test-b']));assert.equal(JSON.stringify(s.selectLayer(page,['test-a','test-b'],'test-a',true)),JSON.stringify(['test-b']));const other=page.sections[1].children[0].id;assert.equal(JSON.stringify(s.selectLayer(page,['test-a'],other,true)),JSON.stringify([other]));});
test('group membership persists and clicking a member selects the group',()=>{const doc=s.groupSelection(fixture(),ids.slice(0,2),'test-group');assert.ok(d.validDocument(JSON.parse(JSON.stringify(doc))));assert.equal(s.selectLayer(doc.pages[0],[],'test-a').length,2);assert.ok(layers(s.groupSelection(doc,ids.slice(0,2),undefined)).every(l=>!l.groupId));});
test('marquee excludes locked or hidden layers and expands group members',()=>{let doc=fixture();layers(doc)[1].locked=true;layers(doc)[2].hidden=true;assert.equal(JSON.stringify(s.marqueeSelection(doc.pages[0],doc.pages[0].sections[0].id,{x:0,y:0,width:800,height:500},'desktop')),JSON.stringify(['test-a']));doc=s.groupSelection(fixture(),ids.slice(0,2),'test-group');assert.equal(s.marqueeSelection(doc.pages[0],doc.pages[0].sections[0].id,{x:10,y:20,width:1,height:1},'desktop').length,2);});
test('batch movement is immutable and preserves relative spacing',()=>{const doc=fixture(),before=JSON.stringify(doc),next=s.translateSelection(doc,ids,'desktop',24,-8);assert.equal(JSON.stringify(doc),before);assert.equal(layers(next)[0].box.x,34);assert.equal(layers(next)[1].box.x,224);assert.equal(layers(next)[2].box.y,242);assert.ok(d.validDocument(next));});
test('movement clamps the entire group together at bounds',()=>{const doc=fixture(),next=s.translateSelection(doc,ids,'desktop',20000,0);assert.equal(layers(next)[2].box.x,10000);assert.equal(layers(next)[1].box.x-layers(next)[0].box.x,190);});
test('mobile group movement never changes desktop geometry',()=>{const doc=fixture(),before=JSON.stringify(layers(doc).map(l=>l.box)),next=s.translateSelection(doc,ids,'mobile',8,10);assert.equal(JSON.stringify(layers(next).map(l=>l.box)),before);assert.equal(d.boxAt(layers(next)[0],'mobile').x,d.boxAt(layers(doc)[0],'mobile').x+8);});
test('all six alignment modes align geometric box edges or centers',()=>{for(const mode of ['left','center','right','top','middle','bottom']){const doc=s.alignSelection(fixture(),ids,'desktop',mode),boxes=layers(doc).map(l=>l.box),coordinates=boxes.map(b=>mode==='left'?b.x:mode==='right'?b.x+b.width:mode==='center'?b.x+b.width/2:mode==='top'?b.y:mode==='bottom'?b.y+b.height:b.y+b.height/2);assert.ok(coordinates.every(v=>v===coordinates[0]),mode);}});
test('distribution uses equal gaps with varying sizes and fixes the outside edges',()=>{for(const axis of ['x','y']){const doc=fixture(),next=s.distributeSelection(doc,ids,'desktop',axis),b=layers(next).map(l=>l.box),size=axis==='x'?'width':'height';assert.equal(b[1][axis]-(b[0][axis]+b[0][size]),b[2][axis]-(b[1][axis]+b[1][size]));assert.equal(b[0][axis],layers(doc)[0].box[axis]);assert.equal(b[2][axis],layers(doc)[2].box[axis]);}});
test('scaling respects a common origin and scales text font size',()=>{const doc=s.scaleSelection(fixture(),ids,'desktop',2),b=layers(doc);assert.equal(b[0].box.x,10);assert.equal(b[0].box.width,200);assert.equal(b[0].box.fontSize,40);assert.equal(b[1].box.x,390);assert.equal(b[1].box.height,200);});
test('invalid scale and oversize operation do not partly apply',()=>{const doc=fixture();for(const factor of [NaN,Infinity,0,-1,1000])assert.equal(s.scaleSelection(doc,ids,'desktop',factor),doc);});
test('locked and hidden layers do not move',()=>{const doc=fixture();layers(doc)[1].locked=true;layers(doc)[2].hidden=true;const next=s.translateSelection(doc,ids,'desktop',24,10);assert.equal(layers(next)[1].box.x,200);assert.equal(layers(next)[2].box.x,500);});
test('cross-section and auto-layout transformations are rejected',()=>{const doc=fixture(),other=doc.pages[0].sections[1].children[0].id;assert.equal(s.translateSelection(doc,['test-a',other],'desktop',10,10),doc);doc.pages[0].sections[0].layout='row';assert.equal(s.alignSelection(doc,ids,'desktop','left'),doc);});
test('Shift resize preserves ratio and obeys minimum/maximum dimensions',()=>{const b=layers(fixture())[0].box;for(const delta of [-10000,10,10000]){const next=s.resizeProportional(b,delta,0,true);assert.equal(next.width/next.height,2);assert.ok(next.width>=10&&next.width<=5000&&next.height>=10&&next.height<=10000);}});
test('group IDs reject unsafe strings and legacy layers without group remain valid',()=>{const doc=fixture();assert.ok(d.validDocument(doc));layers(doc)[0].groupId='<script>';assert.equal(d.validDocument(doc),false);});
